---
galaxy_info:
  role_name: graphite
  author: Yinchuan Song (Red Hat)
  description: Graphite, Carbon, and Statsite for Debian 13
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - trixie
  galaxy_tags:
    - monitoring
    - graphite
    - metrics
    - carbon
    - statsd

dependencies: []
